"""init 19 tables (Integer PK, force_pwd) Phase B

Revision ID: 52b0d6fe8e10
Revises: 
Create Date: 2026-08-19 14:57:22.713940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b0d6fe8e10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_key', sa.String(length=50), nullable=False, comment='子页键'),
    sa.Column('content', sa.JSON(), nullable=True, comment='富文本/结构化内容'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_key')
    )
    op.create_table('about_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False, comment='history/brand_history'),
    sa.Column('year', sa.String(length=20), nullable=False, comment="年份（兼容'2018 至今'）"),
    sa.Column('title', sa.String(length=200), nullable=False, comment='事件标题'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='描述'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.CheckConstraint("type IN ('history','brand_history')", name='ck_timeline_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True, comment='标题（选填）'),
    sa.Column('image', sa.String(length=255), nullable=False, comment='图片路径'),
    sa.Column('link_url', sa.String(length=512), nullable=True, comment='跳转链接（站内/外链）'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True, comment='起（NULL 表示长期）'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='止（超出自动隐藏）'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.CheckConstraint('end_at IS NULL OR start_at IS NULL OR end_at >= start_at', name='ck_banner_time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('info_key', sa.String(length=50), nullable=False, comment='键'),
    sa.Column('info_value', sa.Text(), nullable=True, comment='值'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info_key')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dept_name', sa.String(length=128), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='上级部门（自关联）'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False, comment='industry/campus'),
    sa.Column('title', sa.String(length=120), nullable=False, comment='岗位名称'),
    sa.Column('count', sa.Integer(), nullable=True, comment='招聘人数'),
    sa.Column('location', sa.String(length=120), nullable=True, comment='工作地点'),
    sa.Column('salary_desc', sa.String(length=255), nullable=True, comment='薪资说明'),
    sa.Column('duty', sa.Text(), nullable=True, comment='岗位职责（富文本）'),
    sa.Column('requirement', sa.Text(), nullable=True, comment='任职要求（富文本）'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='投递邮箱'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.CheckConstraint("category IN ('industry','campus')", name='ck_job_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False, comment='industry/company'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图 url'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='摘要'),
    sa.Column('content', sa.Text(), nullable=True, comment='正文（富文本）'),
    sa.Column('source', sa.String(length=200), nullable=True, comment='来源（转载标注）'),
    sa.Column('author', sa.String(length=50), nullable=True, comment='作者'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('views', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('pub_status', sa.String(length=20), nullable=False, comment='发布状态'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True, comment='截止时间'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.CheckConstraint("category IN ('industry','company')", name='ck_news_category'),
    sa.CheckConstraint("pub_status IN ('draft','published','offline')", name='ck_news_pub_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='分类名称（如 客厅）'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='上级分类'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='系列名称（如 智能照明）'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限码'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='权限名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='menu/action'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父权限（权限树）'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint("type IN ('menu','action')", name='ck_sys_permission_type'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_permission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色编码（机器键）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=True, comment='网站名称'),
    sa.Column('logo', sa.String(length=255), nullable=True, comment='Logo 路径'),
    sa.Column('icp', sa.String(length=50), nullable=True, comment='ICP 备案号'),
    sa.Column('copyright', sa.String(length=255), nullable=True, comment='版权文案'),
    sa.Column('slider_interval', sa.Integer(), nullable=False, comment='轮播间隔（秒）'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='页面路由'),
    sa.Column('pv', sa.Integer(), nullable=False, comment='当日 PV'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'path', name='uq_visit_stat_date_path')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='所属空间分类'),
    sa.Column('series_id', sa.Integer(), nullable=True, comment='所属系列'),
    sa.Column('product_code', sa.String(length=64), nullable=False, comment='产品编号/产品ID'),
    sa.Column('name', sa.String(length=120), nullable=False, comment='产品名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='产品描述（富文本）'),
    sa.Column('spec', sa.JSON(), nullable=True, comment='规格参数（JSON 键值）'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图片 url'),
    sa.Column('images', sa.JSON(), nullable=True, comment='其他图片 url 数组'),
    sa.Column('pub_status', sa.String(length=20), nullable=False, comment='发布状态'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='置顶/首页推荐'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('views', sa.Integer(), nullable=False, comment='浏览量'),
    sa.Column('related_products', sa.JSON(), nullable=True, comment='搭配产品 ID 数组（2-4）'),
    sa.Column('price_desc', sa.String(length=255), nullable=True, comment='价格说明文本（不存真实价格）'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.CheckConstraint("pub_status IN ('on_shelf','off_shelf','draft')", name='ck_product_pub_status'),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['product_series.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('sys_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名（唯一）'),
    sa.Column('password_hash', sa.String(length=100), nullable=False, comment='bcrypt 密文'),
    sa.Column('cn_name', sa.String(length=64), nullable=True, comment='中文名'),
    sa.Column('en_name', sa.String(length=64), nullable=True, comment='英文名'),
    sa.Column('dept_id', sa.Integer(), nullable=True, comment='部门编号'),
    sa.Column('gender', sa.String(length=8), nullable=True, comment='性别：男/女/保密'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='邮箱'),
    sa.Column('position', sa.String(length=64), nullable=True, comment='岗位'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色编号（单一角色）'),
    sa.Column('force_pwd', sa.SmallInteger(), nullable=False, comment='是否强制改密（1需改/0否）'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.CheckConstraint("gender IS NULL OR gender IN ('男','女','保密')", name='ck_sys_user_gender'),
    sa.ForeignKeyConstraint(['dept_id'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名（2-20 字符）'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('appt_type', sa.String(length=20), nullable=False, comment='showroom/factory'),
    sa.Column('appt_date', sa.Date(), nullable=True, comment='期望日期（不早于今天）'),
    sa.Column('appt_slot', sa.String(length=10), nullable=True, comment='morning/afternoon'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注（≤200 字）'),
    sa.Column('source_page', sa.String(length=255), nullable=True, comment='来源页面'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态'),
    sa.Column('handle_remark', sa.String(length=500), nullable=True, comment='处理备注'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True, comment='处理时间'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='提交 IP'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.CheckConstraint("appt_slot IS NULL OR appt_slot IN ('morning','afternoon')", name='ck_appt_slot'),
    sa.CheckConstraint("appt_type IN ('showroom','factory')", name='ck_appt_type'),
    sa.CheckConstraint("status IN ('pending','confirmed','completed','cancelled')", name='ck_appt_status'),
    sa.ForeignKeyConstraint(['handler_id'], ['sys_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='姓名（2-20 字符）'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='邮箱（选填）'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='咨询类型'),
    sa.Column('content', sa.String(length=500), nullable=False, comment='咨询内容（10-500 字）'),
    sa.Column('source_page', sa.String(length=255), nullable=True, comment='来源页面'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='弱关联产品'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态'),
    sa.Column('handle_remark', sa.String(length=500), nullable=True, comment='处理备注'),
    sa.Column('handler_id', sa.Integer(), nullable=True, comment='处理人'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True, comment='处理时间'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='提交 IP'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.CheckConstraint("status IN ('pending','processed','closed')", name='ck_msg_status'),
    sa.CheckConstraint("type IN ('product','cooperation','aftersale','other')", name='ck_msg_type'),
    sa.ForeignKeyConstraint(['handler_id'], ['sys_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作人'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='操作人名称（快照）'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='模块'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='动作'),
    sa.Column('detail', sa.Text(), nullable=True, comment='详情描述'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='IP'),
    sa.Column('is_activate', sa.SmallInteger(), nullable=False, comment='1启用/0禁用（记录级总开关）'),
    sa.Column('created_at', sa.String(length=64), nullable=False, comment='创建人（登录名/姓名）'),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.String(length=64), nullable=False, comment='修改人（登录名/姓名）'),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='修改时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删时间；NULL 表示未删除'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_log')
    op.drop_table('message')
    op.drop_table('appointment')
    op.drop_table('sys_user')
    op.drop_table('sys_role_permission')
    op.drop_table('product')
    op.drop_table('visit_stat')
    op.drop_table('system_settings')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('product_series')
    op.drop_table('product_category')
    op.drop_table('news')
    op.drop_table('job')
    op.drop_table('department')
    op.drop_table('company_info')
    op.drop_table('banner')
    op.drop_table('about_timeline')
    op.drop_table('about_info')
    # ### end Alembic commands ###
