"""system_settings add baidu_map_ak (Phase F/G: 前台地图 AK 后台可配置)

Revision ID: 9c4a2f7b1d03
Revises: ef3d11f54204
Create Date: 2026-08-20 14:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4a2f7b1d03'
down_revision: Union[str, Sequence[str], None] = 'ef3d11f54204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('baidu_map_ak', sa.String(length=255), nullable=True, comment='百度地图 JS API AK（前台联系页地图）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'baidu_map_ak')
    # ### end Alembic commands ###
