"""system_settings add map_image (前台联系页地图图片)

Revision ID: a7e9d2c4b501
Revises: 9c4a2f7b1d03
Create Date: 2026-08-20 15:32:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e9d2c4b501'
down_revision: Union[str, Sequence[str], None] = '9c4a2f7b1d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('map_image', sa.String(length=255), nullable=True, comment='联系页地图图片（点击跳转百度地图）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'map_image')
    # ### end Alembic commands ###
