"""news add images gallery (Phase E fix)

Revision ID: ef3d11f54204
Revises: 52b0d6fe8e10
Create Date: 2026-08-19 17:52:58.231892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3d11f54204'
down_revision: Union[str, Sequence[str], None] = '52b0d6fe8e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('images', sa.JSON(), nullable=True, comment='图集（多图 url 数组，第一张为封面）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'images')
    # ### end Alembic commands ###
